name: Generate TOC

on:
  push:
    branches:
      - main

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Table of Contents
        uses: technote-space/toc-generator@v4
