name: Update Links in README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight (optional)

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate list of links for all HTML files
        run: |
          # Output file to store the generated links
          echo "## Repository Links" > LINKS.md
          echo "" >> LINKS.md
          
          # Directory to search for HTML files (recursively)
          DIRECTORY="Germany"

          # Find all HTML files in the directory and generate links
          find $DIRECTORY -type f -name "*.html" | sort | while read file; do
            # Create the link for each file (using the correct GitHub Pages path)
            file_url="https://m-hosseini80.github.io/Germany/${file#./}"
            echo "- [${file#./}](${file_url})" >> LINKS.md
          done

      - name: Update README with generated links
        run: |
          # Append the generated links to the README file
          cat LINKS.md >> README.md

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Auto-update file links in README"
          git push
