name: Update README with HTML Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Find all HTML files and generate README links
        run: |
          # Find all HTML files and generate markdown links
          find . -type f -name "*.html" | sort | while read file; do
            # Get the relative path of the file
            relative_path=$(echo $file | sed 's|^\./||')
            # Replace / with the GitHub Pages URL structure
            url="https://m-hosseini80.github
