name: Update README with HTML Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Find all HTML files and generate README links
        run: |
          # Find all HTML files and generate markdown links
          find . -type f -name "*.html" | sort | while read file; do
            # Get the relative path of the file
            relative_path=$(echo "$file" | sed 's|^\./||')
            # Replace / with the GitHub Pages URL structure
            url="https://m-hosseini80.github.io/Germany/$relative_path"
            # Add the link to the list (you can customize this to append the output to a README file)
            echo "- [$relative_path]($url)" >> links.txt
          done
          
      - name: Check and update README with new links
        run: |
          # Ensure there are no duplicate links in the README
          # First, check if the "Repository Links" section exists and append if not
          if ! grep -q "## Repository Links" README.md; then
            echo "## Repository Links" >> README.md
          fi
          
          # Check if the links already exist and add only new ones
          for link in $(cat links.txt); do
            if ! grep -q "$link" README.md; then
              echo "$link" >> README.md
            fi
          done

      - name: Commit and push updated README
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update README with new HTML links'
